language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script: mvn clean test -U
before_install: cd ProtocolLib
install: true
notifications:
  email:
    recipients:
      - "dmulloy2@live.com"
    on_success: change
    on_failure: always