global:
  metrics: true
  
  # Automatically compile structure modifiers 
  background compiler: true
  
  # Disable version checking for the given Minecraft version. Backup your world first!
  ignore version check: 
  
  # Override the starting injecting method
  injection method: 
  
  # Whether or not to enable the filter command
  debug: false
  
  # Whether or not to print a stack trace for every warning
  detailed error: false
  
  # The engine used by the filter command
  script engine: JavaScript
  
  suppressed reports: